safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 深夜两点
host: localhost
desc: 深夜两点的技术博客

custom:
    category:
        default: 杂言杂语
        coding: 编程
        dataprocess: 数据处理和存储
        devtools: 开发工具
        dsl: DSL
        frontend: 前端
        messagequeue: 消息队列
        midware: 中间件

    categories:
      - name:  default
        title: 杂言杂语

      - name:  coding
        title: 编程

      - name:  dataprocess
        title: 数据处理和存储

      - name:  devtools
        title: 开发工具

      - name:  dsl
        title: DSL

      - name:  frontend
        title: 前端

      - name:  messagequeue
        title: 消息队列

      - name:  midware
        title: 中间件

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: 深夜两点
        email: deepnighttwo@gmail.com
        disqus: your-disqus-short-name              # Disqus缩略标识
        gcse: 006032891784202562981:he3thw5c4uq     # Google自定义搜索标识ID
        github: deepnighttwo                        # GitHub账号
        gravatar: 44365c280aaf29c8978ff5b643abee38  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
